name: 2 - Publicador (08h, 12h, 18h BRT)
on:
  schedule:
    # 07:45 BRT = 10:45 UTC
    - cron: '45 10 * * *'
    # 11:45 BRT = 14:45 UTC
    - cron: '45 14 * * *'
    # 17:45 BRT = 20:45 UTC
    - cron: '45 20 * * *'
  workflow_dispatch:
jobs:
  run-publicador:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python src/publicador.py
        env:
          INSTAGRAM_USER_ID: ${{ secrets.INSTAGRAM_USER_ID }}
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
          IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      - name: Atualizar JSON marcando postado
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git add database/
          git commit -m "Auto: Post publicado no Instagram" || exit 0
          git push
